name: 'Update Markdown TOC'

on:
  push:
    branches:
      - master
jobs:
  MainJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Markdown TOC
        run: |
          mkdir -p ~/.local/bin
          curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc -o ~/.local/bin/gh-md-toc
          chmod a+x ~/.local/bin/gh-md-toc
          export PATH=$PATH:~/.local/bin
          ./toc-generator.sh
      - uses: EndBug/add-and-commit@v7
        with:
          add: '*.md'    
          message: 'doc: update md TOC'